steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'frontend/Dockerfile.prod'
      - '--build-arg'
      - 'VITE_API_URL=https://mimo-backend-qjhc3e7jla-ew.a.run.app'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mimo-repo/frontend:latest'
      - './frontend'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mimo-repo/frontend:latest'
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/mimo-repo/frontend:latest'
