"""Add closed_at to accounts for soft delete

Revision ID: 20aec2232f0d
Revises: a0c1229894fe
Create Date: 2025-12-05 17:25:06.696782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20aec2232f0d'
down_revision: Union[str, None] = 'a0c1229894fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'closed_at')
    # ### end Alembic commands ###
