"""Add couple mode features (invitations, household status, transaction ownership)

Revision ID: 5de877f00589
Revises: cc3d20f5ba8f
Create Date: 2025-12-07 21:16:01.608637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5de877f00589'
down_revision: Union[str, None] = 'cc3d20f5ba8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first (with IF NOT EXISTS logic)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE invitationtype AS ENUM ('EXISTING_USER');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE invitationstatus AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE householdstatus AS ENUM ('ACTIVE', 'ARCHIVED', 'MERGED_INTO_COUPLE');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE transactionownertype AS ENUM ('PERSONAL', 'SHARED');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inviter_user_id', sa.String(length=36), nullable=False),
    sa.Column('invitee_user_id', sa.String(length=36), nullable=False),
    sa.Column('type', postgresql.ENUM('EXISTING_USER', name='invitationtype', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='invitationstatus', create_type=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('households', sa.Column('status', postgresql.ENUM('ACTIVE', 'ARCHIVED', 'MERGED_INTO_COUPLE', name='householdstatus', create_type=False), nullable=True))
    op.execute("UPDATE households SET status = 'ACTIVE' WHERE status IS NULL")
    op.alter_column('households', 'status', nullable=False)
    op.add_column('households', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.add_column('households', sa.Column('merged_into_household_id', sa.String(length=36), nullable=True))
    op.add_column('transactions', sa.Column('owner_type', postgresql.ENUM('PERSONAL', 'SHARED', name='transactionownertype', create_type=False), nullable=True))
    op.add_column('transactions', sa.Column('owner_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_owner_user_id'), 'transactions', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['owner_user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_owner_user_id'), table_name='transactions')
    op.drop_column('transactions', 'owner_user_id')
    op.drop_column('transactions', 'owner_type')
    op.drop_column('households', 'merged_into_household_id')
    op.drop_column('households', 'archived_at')
    op.drop_column('households', 'status')
    op.drop_table('invitations')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS transactionownertype")
    op.execute("DROP TYPE IF EXISTS householdstatus")
    op.execute("DROP TYPE IF EXISTS invitationstatus")
    op.execute("DROP TYPE IF EXISTS invitationtype")
    # ### end Alembic commands ###
