"""add_goal_id_to_transactions_and_goal_fields

Revision ID: 839dbd115223
Revises: ed4fa7291286
Create Date: 2026-08-24 18:35:13.922751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839dbd115223'
down_revision: Union[str, None] = 'ed4fa7291286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('monthly_contribution', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('goals', sa.Column('account_id', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('destination_account_id', sa.String(), nullable=True))
    op.alter_column('goals', 'target_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_index(op.f('ix_goals_account_id'), 'goals', ['account_id'], unique=False)
    op.create_index(op.f('ix_goals_destination_account_id'), 'goals', ['destination_account_id'], unique=False)
    op.create_foreign_key(None, 'goals', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'goals', 'accounts', ['destination_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('goal_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_goal_id'), 'transactions', ['goal_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_goal_id'), table_name='transactions')
    op.drop_column('transactions', 'goal_id')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_constraint(None, 'goals', type_='foreignkey')
    op.drop_index(op.f('ix_goals_destination_account_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_account_id'), table_name='goals')
    op.alter_column('goals', 'target_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('goals', 'destination_account_id')
    op.drop_column('goals', 'account_id')
    op.drop_column('goals', 'monthly_contribution')
    # ### end Alembic commands ###
