"""Add recurring_template_id to transactions

Revision ID: acf8a934b57a
Revises: 8efa0691944c
Create Date: 2025-12-05 20:04:51.570176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf8a934b57a'
down_revision: Union[str, None] = '8efa0691944c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('recurring_template_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_recurring_template_id'), 'transactions', ['recurring_template_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'recurring_templates', ['recurring_template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_recurring_template_id'), table_name='transactions')
    op.drop_column('transactions', 'recurring_template_id')
    # ### end Alembic commands ###
