"""Add state column to transactions and notifications table

Revision ID: cc3d20f5ba8f
Revises: acf8a934b57a
Create Date: 2025-12-07 17:48:36.913212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3d20f5ba8f'
down_revision: Union[str, None] = 'acf8a934b57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create TransactionState enum type first
    transaction_state_enum = sa.Enum('REALIZED', 'PROJECTED', 'PENDING', name='transactionstate')
    transaction_state_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('VALIDATION_REQUIRED', 'REMINDER', 'INFO', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('state', sa.Enum('REALIZED', 'PROJECTED', 'PENDING', name='transactionstate'), nullable=False, server_default='REALIZED'))
    op.create_index(op.f('ix_transactions_state'), 'transactions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_state'), table_name='transactions')
    op.drop_column('transactions', 'state')
    op.drop_table('notifications')
    # ### end Alembic commands ###
