import type { Transaction, Account, Category, Goal } from '@/types'

export const sampleTransactions: Transaction[] = [
  {
    id: '1',
    name: 'Salaire mensuel',
    amount: 2500,
    type: 'income',
    status: 'realized',
    attribution: 'personal',
    categoryId: 'cat-salary',
    accountId: 'acc-1',
    date: new Date(2024, 11, 1).toISOString(),
    isRecurring: true,
    createdBy: 'user',
  },
  {
    id: '2',
    name: 'Loyer',
    amount: 850,
    type: 'expense',
    status: 'realized',
    attribution: 'shared',
    categoryId: 'cat-housing',
    accountId: 'acc-1',
    date: new Date(2024, 11, 5).toISOString(),
    isRecurring: true,
    createdBy: 'user',
  },
  {
    id: '3',
    name: 'Courses Carrefour',
    amount: 125,
    type: 'expense',
    status: 'pending',
    attribution: 'shared',
    categoryId: 'cat-food',
    accountId: 'acc-1',
    date: new Date().toISOString(),
    isRecurring: false,
    createdBy: 'user',
  },
  {
    id: '4',
    name: 'Abonnement Netflix',
    amount: 14,
    type: 'expense',
    status: 'realized',
    attribution: 'shared',
    categoryId: 'cat-entertainment',
    accountId: 'acc-1',
    date: new Date(2024, 11, 15).toISOString(),
    isRecurring: true,
    createdBy: 'user',
  },
  {
    id: '5',
    name: 'Restaurant Le Gourmet',
    amount: 65,
    type: 'expense',
    status: 'pending',
    attribution: 'personal',
    categoryId: 'cat-dining',
    accountId: 'acc-1',
    date: new Date().toISOString(),
    isRecurring: false,
    createdBy: 'user',
  },
]

export const sampleAccounts: Account[] = [
  {
    id: 'acc-1',
    name: 'Compte Courant Principal',
    type: 'checking',
    bank: 'BNP Paribas',
    balance: 2450,
    userId: 'user',
  },
  {
    id: 'acc-2',
    name: 'Livret A',
    type: 'savings',
    bank: 'Crédit Agricole',
    balance: 5800,
    userId: 'user',
  },
  {
    id: 'acc-3',
    name: 'Carte Visa',
    type: 'credit',
    bank: 'BNP Paribas',
    balance: -450,
    userId: 'user',
  },
]

export const sampleCategories: Category[] = [
  {
    id: 'cat-salary',
    name: 'Salaire',
    type: 'income',
    color: '#4ECDC4',
    icon: '💰',
    userId: 'user',
  },
  {
    id: 'cat-housing',
    name: 'Logement',
    type: 'expense',
    color: '#FF6B6B',
    icon: '🏠',
    monthlyBudget: 900,
    userId: 'user',
  },
  {
    id: 'cat-food',
    name: 'Courses',
    type: 'expense',
    color: '#45B7D1',
    icon: '🍔',
    monthlyBudget: 400,
    userId: 'user',
  },
  {
    id: 'cat-entertainment',
    name: 'Loisirs',
    type: 'expense',
    color: '#C77DFF',
    icon: '🎬',
    monthlyBudget: 150,
    userId: 'user',
  },
  {
    id: 'cat-dining',
    name: 'Restaurants',
    type: 'expense',
    color: '#FFD93D',
    icon: '🍽️',
    monthlyBudget: 200,
    userId: 'user',
  },
  {
    id: 'cat-transport',
    name: 'Transport',
    type: 'expense',
    color: '#6BCF7F',
    icon: '🚗',
    monthlyBudget: 150,
    userId: 'user',
  },
]

export const sampleGoals: Goal[] = [
  {
    id: 'goal-1',
    name: 'Vacances à Bali',
    targetAmount: 3000,
    currentAmount: 1250,
    deadline: new Date(2025, 7, 1).toISOString(),
    icon: '✈️',
    userId: 'user',
  },
  {
    id: 'goal-2',
    name: 'Nouvelle voiture',
    targetAmount: 15000,
    currentAmount: 4500,
    deadline: new Date(2026, 5, 1).toISOString(),
    icon: '🚗',
    userId: 'user',
  },
  {
    id: 'goal-3',
    name: 'Fonds d\'urgence',
    targetAmount: 5000,
    currentAmount: 3200,
    deadline: new Date(2025, 11, 31).toISOString(),
    icon: '💰',
    userId: 'user',
  },
]
